In [ ]:
import numpy as np

In [ ]:
a = np.zeros(5)                  #return a new array of a given shape and type, filled with zero.

In [ ]:
a

array([0., 0., 0., 0., 0.])

In [ ]:
a.ndim

1

In [ ]:
b = np.zeros((3,4))

In [ ]:
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
b.ndim

2

In [ ]:
i = np.ones((3,4))

In [ ]:
i

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
i.ndim

2

In [ ]:
s = np.array([[2,2,2],[10,20,40]])

In [ ]:
s

array([[ 2,  2,  2],
       [10, 20, 40]])

In [ ]:
s.ndim

2

In [ ]:
arr = np.zeros((1,3,4))

In [ ]:
arr

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
arr.ndim

3

In [ ]:
arr = np.zeros((1,1,3,4))

In [ ]:
arr

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [ ]:
arr.ndim

4

In [ ]:
arr = np.zeros((1,1,1,3,4))

In [ ]:
arr

array([[[[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]]])

In [ ]:
arr.ndim

5

In [ ]:
arr = np.ones((3,4))

In [ ]:
arr.ndim

2

In [ ]:
arr.shape

(3, 4)

In [ ]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
arr + 5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [ ]:
arr * 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [ ]:
a = arr * 5

In [ ]:
a

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [ ]:
a - 1

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [ ]:
np.eye(5)           #Return a 2-D array with ones on the diagonal and zeros elsewhere.

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
np.eye(5, dtype = int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
np.empty((3,4))          #Return a new array of given shape and type, without initializing entries.

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
#optional random module

import random
random.choice ((1,2,3,4,5))

4

In [ ]:
random.choice(("arun"))

'a'

In [ ]:
random.random()          #random number will be generated between 0(included) to 1(excluded).

0.11198753147544516

In [ ]:
lis = [1,2,3,4,5]

In [ ]:
type(lis)

list

In [ ]:
lis

[1, 2, 3, 4, 5]

In [ ]:
random.shuffle(lis)

In [ ]:
lis

[5, 3, 4, 2, 1]

In [ ]:
random.uniform(7,14)

8.949742148761464

In [ ]:
random.uniform(10,12)

11.489776051764892

In [ ]:
np.random.random_sample()

0.5158435809317609

In [ ]:
np.random.random_sample(5)

array([0.29782139, 0.80505535, 0.25047483, 0.6532252 , 0.50025956])

In [ ]:
np.random.rand(2,3)

array([[0.27588524, 0.73130373, 0.74102433],
       [0.76702182, 0.55496118, 0.31982795]])

In [ ]:
a = [2,3]

In [ ]:
arr = a

In [ ]:
arr

[2, 3]

In [ ]:
#Conditions on array

arr1 = np.random.randint(1,10,(5,6))

In [ ]:
arr1

array([[7, 5, 8, 9, 6, 2],
       [9, 9, 2, 5, 6, 9],
       [6, 1, 8, 5, 6, 6],
       [2, 4, 5, 5, 6, 2],
       [9, 6, 7, 4, 3, 6]])

In [ ]:
arr1.shape

(5, 6)

In [ ]:
arr1.size

30

In [ ]:
arr1.ndim

2

In [ ]:
arr1 > 3              #The number is greater than >3 than ita true or else false.

array([[ True,  True,  True,  True,  True, False],
       [ True,  True, False,  True,  True,  True],
       [ True, False,  True,  True,  True,  True],
       [False,  True,  True,  True,  True, False],
       [ True,  True,  True,  True, False,  True]])

In [ ]:
arr1 [arr1 > 3]

array([7, 5, 8, 9, 6, 9, 9, 5, 6, 9, 6, 8, 5, 6, 6, 4, 5, 5, 6, 9, 6, 7,
       4, 6])

In [ ]:
arr1 [arr1 < 3]

array([2, 2, 1, 2, 2])

In [ ]:
arr1 < 3

array([[False, False, False, False, False,  True],
       [False, False,  True, False, False, False],
       [False,  True, False, False, False, False],
       [ True, False, False, False, False,  True],
       [False, False, False, False, False, False]])

In [ ]:
arr1

array([[7, 5, 8, 9, 6, 2],
       [9, 9, 2, 5, 6, 9],
       [6, 1, 8, 5, 6, 6],
       [2, 4, 5, 5, 6, 2],
       [9, 6, 7, 4, 3, 6]])

In [ ]:
arr1 [0]                           #Row

array([7, 5, 8, 9, 6, 2])

In [ ]:
arr1 [1]

array([9, 9, 2, 5, 6, 9])

In [ ]:
arr1 [1][3]            #To access elements in the array.

5

In [ ]:
arr1 [0:2]             #Access two rows.

array([[7, 5, 8, 9, 6, 2],
       [9, 9, 2, 5, 6, 9]])

In [ ]:
arr1 [0:3]             #Access three rows.

array([[7, 5, 8, 9, 6, 2],
       [9, 9, 2, 5, 6, 9],
       [6, 1, 8, 5, 6, 6]])

In [ ]:
arr1 [0:3,[0,2,]]      #0 to 2nd row and 0th to 2nd column.

array([[7, 8],
       [9, 2],
       [6, 8]])

In [ ]:
#Slicing on both rows and columns.

arr1

array([[7, 5, 8, 9, 6, 2],
       [9, 9, 2, 5, 6, 9],
       [6, 1, 8, 5, 6, 6],
       [2, 4, 5, 5, 6, 2],
       [9, 6, 7, 4, 3, 6]])

In [ ]:
arr1 [1:4,[0,3]]

array([[9, 5],
       [6, 5],
       [2, 5]])

In [ ]:
#Mathematical operations on two array.

arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,5,(3,3))

In [ ]:
arr1

array([[2, 1, 2],
       [2, 1, 2],
       [2, 1, 1]])

In [ ]:
arr2

array([[3, 1, 2],
       [2, 4, 4],
       [4, 2, 3]])

In [ ]:
arr1 + arr2             #indexwise element addition.

array([[5, 2, 4],
       [4, 5, 6],
       [6, 3, 4]])

In [ ]:
arr1 - arr2             #indexwise element substraction.

array([[-1,  0,  0],
       [ 0, -3, -2],
       [-2, -1, -2]])

In [ ]:
arr1 * arr2             #indexwise element miltiplication

array([[6, 1, 4],
       [4, 4, 8],
       [8, 2, 3]])

In [ ]:
arr1, arr2

(array([[2, 1, 2],
        [2, 1, 2],
        [2, 1, 1]]),
 array([[3, 1, 2],
        [2, 4, 4],
        [4, 2, 3]]))

In [ ]:
arr1 / arr2             #indexwise element divide

array([[0.66666667, 1.        , 1.        ],
       [1.        , 0.25      , 0.5       ],
       [0.5       , 0.5       , 0.33333333]])

In [ ]:
#Matrix multiplication differet from index wise multiplication.

arr1 @ arr2               #First way to do matrix multiplication.

array([[16, 10, 14],
       [16, 10, 14],
       [12,  8, 11]])

In [ ]:
np.dot (arr1 ,arr2)       #Second way to do matrix multiplication.

array([[16, 10, 14],
       [16, 10, 14],
       [12,  8, 11]])

In [ ]:
arr1 / 0                #in python 0 division error will come, but in numpy no error.

<ipython-input-58-f39b50d43667>:1: RuntimeWarning: divide by zero encountered in divide
  arr1 / 0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [ ]:
#Broadcasting

arr = np.zeros((3,4))

In [ ]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr + 5                      #ADD

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [ ]:
arr - 5                      #SUBSTRACT

array([[-5., -5., -5., -5.],
       [-5., -5., -5., -5.],
       [-5., -5., -5., -5.]])

In [ ]:
arr.shape

(3, 4)

In [ ]:
arr.ndim

2

In [ ]:
arr.size

12

In [ ]:
a = np.array([1,2,3,4])

In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
a + arr

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [ ]:
#Transpose

arr1

array([[2, 1, 2],
       [2, 1, 2],
       [2, 1, 1]])

In [ ]:
arr1.T                #In transpose rows becomes columns.

array([[2, 2, 2],
       [1, 1, 1],
       [2, 2, 1]])